version: '3.4'

services:
  camabrs.api:
    image: ${DOCKER_REGISTRY-}camabrsapi
    build:
      context: .
      dockerfile: CamabrS.API/Dockerfile
    depends_on:
      - camabrs-db
       
  camabrs-db:
    image: postgres:latest
    container_name: camabrsdb
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/database:/var/lib/postgresql/data
    ports:
      - 5432:5432