# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repo
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore CamabrS.sln
      
    - name: Build
      run: dotnet build CamabrS.sln --no-restore
      
    - name: Start containers
      run: docker-compose up -d

    - name: Run tests
      run: dotnet test CamabrS.IntegrationTests/CamabrS.IntegrationTests.csproj --no-build --verbosity normal --logger "trx;LogFileName=xtests.trx"

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        trx_files: "/home/runner/work/CamabrS/CamabrS/CamabrS.IntegrationTests/TestResults/xtests.trx"      

    - name: Stop containers
      if: always()
      run: docker-compose down
